### ISSUE TITLE
BVH Streaming?

### ISSUE THREAD

**Issue by spencercap** [omimo/MocapJS#1]
Hi, excellent work here! I'm wondering if you're using Motive, Nexus or something else for the BVH streaming and how that side of things works. We have a small python server reworking the streaming data from Motive here but that's a mess.

**Comment by omimo** [comment]
Hi,

Thanks!

I have a machine learning model ([WalkNet](https://omid.al/projects/WalkNet.html)) which generates movement animation in real-time. The generated data is post-processed to a simple bvh-style format that can be displayed in almost the same way as regular BVH files:

There is a simple socket server (written in Java/Matlab) that sends the bvh header upon initiating a connection, and then streams packets of joint rotations in the same format as bvh channels as soon as they are generated by the machine learning model and post-processed.

**Comment by spencercap** [comment]
Ah, I see the pipeline now- thanks for the reply. If I do a little pre-processing that appends all new joint rotations into a new line (frame) like the BVH format calls for, it sounds like I can work with your BVHStream parser and MoCap.js lib
